### PR TITLE
Fix rcorder issues with dhcp client

### PR DESCRIPTION
**Pull request by pkgdemon**

### CODE REVIEW

**Comment by pkgdemon** [comment]
Current status of tests so far:

Ethernet
* All connected adapters should try to dhcp at boot (pass)
* Connectivity should be tested with ping google.com, and ping6 google.com to ensure both protocols function (pass)
* mDNS connectivity should be tested too and from the system under test (pass)
* Setting a static IP should prevent dhcp from assigning an IP to an adapter (pass)
* Any active ethernet adapter without dhcp or inactive adapter should not delay boot (pass)
* It should be verified that ntpdate runs by checking /var/log/console.log (pass)

Wireless
* Supported wireless modules must load automatically with devmatch (pass)
* Wireless adapter should appear in furybsd-wifi-tool to configure (pass)
* When selecting an adapter to configure in furybsd-wifi-tool wpa_gui should appear (pass)
* Clicking scan should present a list of wireless networks to connect to (pass)
* Double clicking a wireless network should prompt to set a passphrase if encryption is enabled on the access point (pass)
* Entering a passphrase and clicking save should connect to the access point (pass)
* Within 5 seconds the wpa_gui should show connection to access point, and IPV4 address if obtained (pass)
* Connectivity should be tested with ping google.com, and ping6 google.com to ensure both protocols function (pass)
* mDNS connectivity should be tested to and from the system under test (needs testing)
* Upon reboot it should be verified that ntpdate runs by checking /var/log/console.log (needs testing)

**Comment by probonopd** [comment]
Thanks @pkgdemon.

So this solution is too simplisitic/breaks things?

```
sed -i -e 's|^# REQUIRE: .*|# REQUIRE: dhclient DAEMON dbus|g' "${uzip}/usr/local/etc/rc.d/avahi-daemon"
rm "${uzip}/usr/local/etc/rc.d/avahi-daemon-e" || true
sed -i -e 's|^# REQUIRE: .*|# REQUIRE: dhclient NETWORKING syslogd|g' "${uzip}/etc/rc.d/ntpdate"
rm "${uzip}/etc/rc.d/ntpdate-e" || true
```

**Comment by pkgdemon** [comment]
> Thanks @pkgdemon.
> 
> So this solution is too simplisitic/breaks things? (It gave me working date and time.)
> 
> ```
> sed -i -e 's|^# REQUIRE: .*|# REQUIRE: dhclient DAEMON dbus|g' "${uzip}/usr/local/etc/rc.d/avahi-daemon"
> rm "${uzip}/usr/local/etc/rc.d/avahi-daemon-e" || true
> sed -i -e 's|^# REQUIRE: .*|# REQUIRE: dhclient NETWORKING syslogd|g' "${uzip}/etc/rc.d/ntpdate"
> rm "${uzip}/etc/rc.d/ntpdate-e" || true
> ```

For the live media this would work but this would cause problems eventually when a user wants to upgrade.

**Comment by pkgdemon** [comment]
This needs a bit more investigation after further testing one of my systems which I intended to perform the final tests on is using wireless only is getting an IPv6 only nameserver and is unable to reach that nameserver.

**Comment by pkgdemon** [comment]
Furthermore I've noticed some errors at boot that need research.  Also furybsd-wifi-tool needs to provide some kind of progress while netif brings up devices since that can be a slow transition from selecting the wireless adapter to configure to connecting to an AP.

**Comment by pkgdemon** [comment]
> Furthermore I've noticed some errors at boot that need research.
> 
> ```
> Oct  9 17:56:29  kernel: ifconfig: ioctl(SIOCGIFINFO_IN6): Invalid argument
> ```
> 
> Also furybsd-wifi-tool needs to provide some kind of progress while netif brings up devices since that can be a slow transition from selecting the wireless adapter to configure to connecting to an AP.

This error is fixed.  Using the built in tools to obtain IPV6 address by SLAAC resolves the issue of resolv.conf getting clobbered.  It now uses IPV4 and IPV6 name servers as expected.  A little more testing to do to make sure system with wireless works as expected post install.

**Comment by pkgdemon** [comment]
Filed another ticket for hostnames issues after install that seem unrelated.  https://github.com/furybsd/furybsd-livecd/issues/227

**Pull request merged**
