### PR TITLE
Restore GUI installer

### PR DESCRIPTION
**Pull request by pkgdemon**
Reverts furybsd/furybsd-livecd#214

Reverting now that approval for this use case has been granted by foundation. 

* TODO
1.) replace py-dmidecode script with dmidecode from ports so we can avoid having to ship an external script with an alternate license in this repo?  Even better would just be to replace this usage of `py-dmidecode` with built in `sysctl -n` commands to get cpu, oem info etc?  For example...
```
$ sysctl -n hw.model
Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz
```
What else is needed that dmidecode provides and I can provide more example commands?
2.) Remove or replace mp3 sound sample for installation finished with something installed from ports?  Perhaps `freedesktop-sound-theme` or some other pkg has an acceptable sound for installation finished so we do not have to bundle audio content in this repo?
3.) I think we still have an open bug of setting empty password still not working?

### CODE REVIEW

**Comment by probonopd** [comment]
> replace py-dmidecode script with dmidecode from ports

Actually, py-dmidecode uses dmidecode from ports. It is just a tiny script that parses its output so that the output can be used in Python.

> sysctl -n

Looks like what we are looking for is not there:

```
user@FreeBSD$ sysctl -a | grep OptiPlex
user@FreeBSD$ sysctl -a | grep Dell
```

**Comment by probonopd** [comment]
> Remove or replace mp3 sound sample for installation finished with something installed from ports? Perhaps freedesktop-sound-theme or some other pkg has an acceptable sound for installation finished so we do not have to bundle audio content in this repo?

Good ides, I will check this. However I don't think a "large" sourd theme would be justified for just one tiny sound. (By the way, I find the sound very useful, not just cosmetics - you can do other work and get reminded when the install is complete.)

> I think we still have an open bug of setting empty password still not working?

Indeed. `-z` seemingly does not distinguish between an unset and an empty password. Maybe we need to use something like `env | grep`?

**Comment by pkgdemon** [comment]
> > Remove or replace mp3 sound sample for installation finished with something installed from ports? Perhaps freedesktop-sound-theme or some other pkg has an acceptable sound for installation finished so we do not have to bundle audio content in this repo?
> 
> Good ides, I will check this. However I don't think a "large" sourd theme would be justified for just one tiny sound. (By the way, I find the sound very useful, not just cosmetics - you can do other work and get reminded when the install is complete.)
> 
> > I think we still have an open bug of setting empty password still not working?
> 
> Indeed. `-z` seemingly does not distinguish between an unset and an empty password. Maybe we need to use something like `env | grep`?

Would this work to disguish set vs unset?  https://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash

**Comment by pkgdemon** [comment]
> > Remove or replace mp3 sound sample for installation finished with something installed from ports? Perhaps freedesktop-sound-theme or some other pkg has an acceptable sound for installation finished so we do not have to bundle audio content in this repo?
> 
> Good ides, I will check this. However I don't think a "large" sourd theme would be justified for just one tiny sound. (By the way, I find the sound very useful, not just cosmetics - you can do other work and get reminded when the install is complete.)
> 
> > I think we still have an open bug of setting empty password still not working?
> 
> Indeed. `-z` seemingly does not distinguish between an unset and an empty password. Maybe we need to use something like `env | grep`?

I checked and `freedesktop-sound-theme` install requires no other dependencies and only requires `459KiB` of space to download the package.  It cannot consume that much on disk to install these files.  It's worth not having an mp3 in this repo.  https://svnweb.freebsd.org/ports/head/audio/freedesktop-sound-theme/pkg-plist?revision=371234&view=markup

**Comment by pkgdemon** [comment]
Confirmed `freedesktop-sound-theme` uses very little space on disk when installed as well.

```
$ du -h
566K	./stereo
567K	.
$ pwd
/usr/local/share/sounds/freedesktop
$ 
```

**Comment by pkgdemon** [comment]
Why exactly do we need `py-dmidecode` to get system info for this installer?  Is it just to set a suggested hostname in a new screen in the future?  I couldn't recall what was discussed in #furybsd on IRC?

**Comment by pkgdemon** [comment]
Probono I told you wrong.  It was `kenv` that can get all the SMBIOS info you should need:

```
smbios.bios.reldate="03/24/2014"
smbios.bios.vendor="American Megatrends Inc."
smbios.bios.version="3.0c"
smbios.chassis.maker="Supermicro"
smbios.chassis.serial="0123456789"
smbios.chassis.tag="To Be Filled By O.E.M."
smbios.chassis.version="0123456789"
smbios.memory.enabled="268435456"
smbios.planar.location="To be filled by O.E.M."
smbios.planar.maker="Supermicro"
smbios.planar.product="X9DRW"
smbios.planar.serial="VM146S010729"
smbios.planar.tag="To be filled by O.E.M."
smbios.planar.version="0123456789"
smbios.socket.enabled="2"
smbios.socket.populated="2"
smbios.system.family="To be filled by O.E.M."
smbios.system.maker="Silicon Mechanics"
smbios.system.product="Rackform iServ R335.v4"
smbios.system.serial="SM88921"
smbios.system.sku="To be filled by O.E.M."
smbios.system.uuid="011c6f64-134d-11e4-b2da-64a2158b7303"
smbios.system.version="0123456789"
```
I would imagine `py37-freebsd` or one of the other bindings packages should provide the interfaces needed or this can be obtained from env?

**Comment by probonopd** [comment]
> Would this work to distinguish set vs unset?

Thanks for the pointer, this is working for me:

```
#!/bin/sh

if [ -z ${INSTALLER_USER_PASSWORD+x} ] ; then 
  echo "INSTALLER_USER_PASSWORD environment variable is not available"
elif [ -z ${INSTALLER_USER_PASSWORD} ] ; then
  echo "INSTALLER_USER_PASSWORD environment variable is available but is blank"
else
  echo "INSTALLER_USER_PASSWORD environment variable is available and is not blank"
fi
```

I think we can implement a solution using this.

**Comment by probonopd** [comment]
Indeed, `kenv` has everything we need.

**Comment by probonopd** [comment]
`/usr/local/share/sounds/freedesktop/stereo/complete.oga` it is then. However, I cannot get it to play with ogg123... it is as if ogg123 was playing it to the wrong device. After trying to use ogg123 my computer is silent (also when trying to play something in Audacity) until I play a video in the browser, at which time things magically start to work again. Hmmm.

**Comment by probonopd** [comment]
@pkgdemon all points have been addressed but it looks like `py-dmidecode` is not in ports. I will have a try at replacing it with `kenv` after the merge. Please review the changes. Thanks!

**Review by probonopd — COMMENTED** [review]
Implemented changes

**Comment by pkgdemon** [comment]
> Implemented changes

Thank you @probonopd I was just getting ready to reply.  I was looking at this commit and I was confused how it's using the package by just removing the file?  https://github.com/furybsd/furybsd-livecd/commit/eb4f3b0a3a92875fc90486908c2a79e198726c31

**Comment by probonopd** [comment]
`py-dmidecode` is not in ports. I will have a try at replacing it with `kenv` after the merge. Since the whole thing is wrapped in a `try:` statement, no harm should be caused until then, the name "Computer" is used in the meantime.

**Comment by pkgdemon** [comment]
> `py-dmidecode` is not in ports. I will have a try at replacing it with `kenv` after the merge. Since the whole thing is wrapped in a `try:` statement, no harm should be caused until then, the name "Computer" is used in the meantime.

oh ok perfect.  one last thing I would like to do after merge, and doesn't have to be anytime soon is to move this into it's own package so eithers can easily find it like furybsd-xorg-tool, furybsd-wifi-tool and so on.  we can make a ticket and make that improvement down the road.  just something I thought of I think would be nice.  stand by for merge...

**Comment by pkgdemon** [comment]
Added todo to move installer at some point down the road.  https://github.com/furybsd/furybsd-livecd/issues/219

**Comment by probonopd** [comment]
> move this into it's own package

Definitely.

**Pull request merged**
